# Generated by Django 5.1.4 on 2025-02-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_orders_oredrupdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OredrUpdate',
            new_name='OrderUpdate',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='oredr_id',
            new_name='order_id',
        ),
    ]
